#!/bin/bash

Renkler

KIRMIZI='\033[1;31m' YESIL='\033[1;32m' MAVI='\033[1;34m' SARI='\033[1;33m' RESET='\033[0m'

IP Bilgisi Fonksiyonu

ip_info() { clear figlet "IP INFO" | lolcat read -p "IP adresi girin: " ip echo -e "\n[+] IP bilgisi alınıyor..." data=$(curl -s "http://ip-api.com/json/$ip") echo "$data" | jq '. | { IP: .query, Ulke: .country, Sehir: .city, ISP: .isp, Koordinatlar: "

